version: "3.9"

services:
  java_app:
    container_name: java_app
    image: loscallcenterosdeluis2025daw:1.0
    build: .
    ports:
      - 8080:8080
    environment:
      - AUTH0_CLIENT_SECRET=YjEaq3La3Lcv--bLUGkF4PMeGJ-I96nl2t_Nl12kVqwdyCJqY_-f2AlFloMOzpZ6
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_AUTH0_CLIENT_ID=FAsdNp49vHdzGr7XVCXCKSTJoh2oKTqq
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI=https://dev-bb6l82r5jx2gzjjy.us.auth0.com/
      - AUTH0_AUDIENCE=https://dev-bb6l82r5jx2gzjjy.us.auth0.com/api/v2/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://java_db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./src/main/resources:/app/src/main/resources
      - ./src/main/templates:/app/src/main/templates
    depends_on:
      - java_db

  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: